AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  AppName:
    Type: String
    Default: campus-app
  Stage:
    Type: String
    Default: dev
  DeviceTableName:
    Type: String
    Default: DeviceTableMuzaffer

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Cors:
        AllowMethods: "'POST, GET, OPTIONS, PUT'"
        AllowHeaders: "'Accept, Content-Type, Content-Length, Authorization, X-Api-Key'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      Name:
        Fn::Sub: ${AppName}-api-${Stage}
      StageName: !Ref Stage
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: specification/openapi.yml

  GetDevices:
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      Runtime: python3.8
      PackageType: Zip
      FunctionName:
        Fn::Sub: ${AppName}-get-devices-${Stage}
      Description: Get the list of devices
      CodeUri: ./src/devices
      Handler: handler.get_devices
      Policies:
        Version: "2012-10-17"
        Statement: 
          Sid: "ReadWriteTable"
          Effect: "Allow"
          Action: 
            - dynamodb:GetItem
            - dyanmodb:Scan
            - dynamodb:Query
          Resource: 
            Fn::Sub: "arn:aws:dynamodb:*:*:table/${DeviceTableName}"
      Environment:
        Variables:
          DeviceTable:
            Fn::Sub: ${DeviceTableName}

  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      Path:
        Fn::Sub: /${Stage}/${AppName}/serviceRoles/
      RoleName:
        Fn::Sub: ${AppName}-api-execution-role-${Stage}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName:
            Fn::Sub: ${AppName}-api-execution-role-policy-${Stage}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  Fn::Sub: ${GetDevices.Arn}

  DeviceTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
      -
        AttributeName: "DeviceId"
        AttributeType: "N"
      -
        AttributeName: "DeviceName"
        AttributeType: "S"
      -
        AttributeName: "DeviceType"
        AttributeType: "S"
      KeySchema:
      -
        AttributeName: "DeviceId"
        KeyType: "HASH"
      -
        AttributeName: "DeviceName"
        KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "10"
        WriteCapacityUnits: "10"
      TableName:
        Fn::Sub: "${DeviceTableName}"
      GlobalSecondaryIndexes:
      -
        IndexName: "DeviceType"
        KeySchema: 
        -
          AttributeName: "DeviceType"
          KeyType: "HASH"    
        Projection: 
          ProjectionType: "ALL"
        ProvisionedThroughput: 
            ReadCapacityUnits: "10"
            WriteCapacityUnits: "10"