openapi: '3.0.2'
info:
  title: Campus numeric api
  version: '1.0'
  description: API to get data from campus sensors
servers:
  - url: https://api.server.test/v1
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params:
    validateRequestBody: true
    validateRequestParameters: true
  body:
    validateRequestBody: true
    validateRequestParameters: false

components:
  schemas:
    device:
      type: object
      required:
        - "deviceName"
        - "deviceType"
      properties:
        deviceId:
          type: "string"
          description: "Unique id of the device"
        deviceName:
          type: "string"
          description: "Name of the device"
        deviceType:
          type: "string"
          description: "Type of the device"
          enum: ["co2", "pir"]
    devices:
      type: array
      items:
        $ref: '#/components/schemas/device'
paths:
  /devices:
    get:
      description: "Get the list of devices"
      responses:
        '200':
          description: OK
          content:
            application/json:
             schema:
              $ref: '#/components/schemas/devices'
      x-amazon-apigateway-integration:
        credentials:
          Fn::Sub: ${ApiGetRole.Arn}
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDevices.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 3000
        type: "aws_proxy"
    post:
      description: "Post a device"
      responses:
        '200':
          description: OK
          content:
            application/json:
             schema:
              $ref: '#/components/schemas/devices'
      x-amazon-apigateway-integration:
        credentials:
          Fn::Sub: ${ApiPostRole.Arn}
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostDevice.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 3000
        type: "aws_proxy"